-- Criação da tabela T_AGROCARE_AGROPECUARISTA
CREATE TABLE T_AGROCARE_AGROPECUARISTA (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(2000) NOT NULL,
    Number BIGINT NOT NULL,
    Endereco NVARCHAR(2000) NOT NULL,
    NumerosAnimais INT NOT NULL,
    Email NVARCHAR(2000) NOT NULL,
    Password NVARCHAR(2000) NOT NULL,
    Status BIT NOT NULL,
    Planos INT NOT NULL
);

-- Criação da tabela T_AGROCARE_VETERINARIO
CREATE TABLE T_AGROCARE_VETERINARIO (
    Id BIGINT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(2000) NOT NULL,
    NumCrmv NVARCHAR(2000) NOT NULL,
    Especialidade NVARCHAR(2000) NOT NULL,
    Telefone BIGINT NOT NULL,
    Email NVARCHAR(2000) NOT NULL,
    Password NVARCHAR(2000) NOT NULL
);